# -*- coding: utf-8 -*-
import os
import cx_Oracle
from tkinter import *
import tkinter as tk
from subprocess import call

con = cx_Oracle.connect("system/vasumalik1")
cur = con.cursor()

win = tk.Tk()
win.geometry("963x649+240+50")
win.title("HOSTEL MANAGEMENT")

font10 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
font11 = "-family {ENGRAVERS MT} -size 15 -weight bold -slant "  \
"roman -underline 0 -overstrike 0"
font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

Frame1 = Frame(win)
Frame1.place(relx=0.01, rely=0.01, relheight=0.12, relwidth=0.93)
Frame1.configure(relief=GROOVE)
Frame1.configure(borderwidth="2")
Frame1.configure(relief=GROOVE)
#self.Frame1.configure(background="#ffffff")
Frame1.configure(highlightbackground="#ffffff")
Frame1.configure(highlightcolor="black")
Frame1.configure(width=995)

Message1 = Message(Frame1)
Message1.place(relx=0.15, rely=0.11, relheight=0.84, relwidth=0.3)
   # self.Message1.configure(background="#ffffff")
Message1.configure(font=font11)
Message1.configure(foreground="#000000")
Message1.configure(highlightbackground="#ffffff")
Message1.configure(highlightcolor="black")
Message1.configure(text='''YOU CLICKED ON''')
Message1.configure(width=496)



Message2 = Message(Frame1)
Message2.place(relx=0.47, rely=0.12, relheight=0.74, relwidth=0.02)
#Message2.configure(background="#ffffff")
Message2.configure(font=font11)
Message2.configure(foreground="#000000")
Message2.configure(highlightbackground="#ffffff")
Message2.configure(highlightcolor="black")
Message2.configure(text=''':''')
Message2.configure(width=66)

Message3 = Message(Frame1)
Message3.place(relx=0.51, rely=0.109, relheight=0.84, relwidth=0.35)
#self.Message3.configure(background="#ffffff")
Message3.configure(font=font11)
Message3.configure(foreground="#000000")
Message3.configure(highlightbackground="#ffffff")
Message3.configure(highlightcolor="black")
Message3.configure(text=''' STUDENT PERSONA''')
Message3.configure(width=347)

#menubar = Menu(win,font=font9,bg=_bgcolor,fg=_fgcolor)
#win.configure(menu = menubar)

lb0 = LabelFrame(win)
lb0.place(relx=0.01, rely=0.13, relheight=0.865
        , relwidth=0.93)
lb0.configure(relief=GROOVE)
lb0.configure(font=font10)
lb0.configure(foreground="black")
lb0.configure(text='''STUDENT PERSONA''')
lb0.configure(highlightbackground="#ffffff")
lb0.configure(highlightcolor="black")
lb0.configure(width=760)



lb = tk.Label(win, text = 'Enter Stuid')
lb.place(relx=0.035, rely=0.16, height=29, width=300)
lb.configure(activebackground="#ffffff")
lb.configure(activeforeground="black")
lb.configure(background="#ffffff")
lb.configure(disabledforeground="#bfbfbf")
lb.configure(font=font10)
lb.configure(foreground="#000000")
lb.configure(highlightbackground="#ffffff")
lb.configure(highlightcolor="black")

lb2 = tk.Label(win, text =  'Stuid')
lb2.place(relx=0.035, rely=0.28,height=29, width=300)
lb2.configure(activebackground="#ffffff")
lb2.configure(activeforeground="black")
lb2.configure(background="#ffffff")
lb2.configure(disabledforeground="#bfbfbf")
lb2.configure(font=font10)
lb2.configure(foreground="#000000")
lb2.configure(highlightbackground="#ffffff")
lb2.configure(highlightcolor="black")

lb1 = tk.Label(win, text = 'Name')
lb1.place(relx=0.035, rely=0.335,height=29, width=300)
lb1.configure(activebackground="#ffffff")
lb1.configure(activeforeground="black")
lb1.configure(background="#ffffff")
lb1.configure(disabledforeground="#bfbfbf")
lb1.configure(font=font10)
lb1.configure(foreground="#000000")
lb1.configure(highlightbackground="#ffffff")
lb1.configure(highlightcolor="black")

lb3 = tk.Label(win, text = 'Rollno')
lb3.place(relx=0.035, rely=0.39,height=29, width=300)
lb3.configure(activebackground="#ffffff")
lb3.configure(activeforeground="black")
lb3.configure(background="#ffffff")
lb3.configure(disabledforeground="#bfbfbf")
lb3.configure(font=font10)
lb3.configure(foreground="#000000")
lb3.configure(highlightbackground="#ffffff")
lb3.configure(highlightcolor="black")

lb4 = tk.Label(win, text = 'Course Name')
lb4.place(relx=0.035, rely=0.445,height=29, width=300)
lb4.configure(activebackground="#ffffff")
lb4.configure(activeforeground="black")
lb4.configure(background="#ffffff")
lb4.configure(disabledforeground="#bfbfbf")
lb4.configure(font=font10)
lb4.configure(foreground="#000000")
lb4.configure(highlightbackground="#ffffff")
lb4.configure(highlightcolor="black")

lb5 = tk.Label(win, text = "No of sem")
lb5.place(relx=0.035, rely=0.50,height=29, width=300)
lb5.configure(activebackground="#ffffff")
lb5.configure(activeforeground="black")
lb5.configure(background="#ffffff")
lb5.configure(disabledforeground="#bfbfbf")
lb5.configure(font=font10)
lb5.configure(foreground="#000000")
lb5.configure(highlightbackground="#ffffff")
lb5.configure(highlightcolor="black")

lb6 = tk.Label(win, text = "DOB")
lb6.place(relx=0.035, rely=0.555,height=29, width=300)
lb6.configure(activebackground="#ffffff")
lb6.configure(activeforeground="black")
lb6.configure(background="#ffffff")
lb6.configure(disabledforeground="#bfbfbf")
lb6.configure(font=font10)
lb6.configure(foreground="#000000")
lb6.configure(highlightbackground="#ffffff")
lb6.configure(highlightcolor="black")

lb3 = tk.Label(win, text = "Father's Name")
lb3.place(relx=0.035, rely=0.610,height=29, width=300)
lb3.configure(activebackground="#ffffff")
lb3.configure(activeforeground="black")
lb3.configure(background="#ffffff")
lb3.configure(disabledforeground="#bfbfbf")
lb3.configure(font=font10)
lb3.configure(foreground="#000000")
lb3.configure(highlightbackground="#ffffff")
lb3.configure(highlightcolor="black")

lb4 = tk.Label(win, text = "Mother's Name")
lb4.place(relx=0.035, rely=0.665,height=29, width=300)
lb4.configure(activebackground="#ffffff")
lb4.configure(activeforeground="black")
lb4.configure(background="#ffffff")
lb4.configure(disabledforeground="#bfbfbf")
lb4.configure(font=font10)
lb4.configure(foreground="#000000")
lb4.configure(highlightbackground="#ffffff")
lb4.configure(highlightcolor="black")

lb5 = tk.Label(win, text = "Gender")
lb5.place(relx=0.035, rely=0.720,height=29, width=300)
lb5.configure(activebackground="#ffffff")
lb5.configure(activeforeground="black")
lb5.configure(background="#ffffff")
lb5.configure(disabledforeground="#bfbfbf")
lb5.configure(font=font10)
lb5.configure(foreground="#000000")
lb5.configure(highlightbackground="#ffffff")
lb5.configure(highlightcolor="black")

lb6 = tk.Label(win, text = "Address")
lb6.place(relx=0.035, rely=0.775,height=29, width=300)
lb6.configure(activebackground="#ffffff")
lb6.configure(activeforeground="black")
lb6.configure(background="#ffffff")
lb6.configure(disabledforeground="#bfbfbf")
lb6.configure(font=font10)
lb6.configure(foreground="#000000")
lb6.configure(highlightbackground="#ffffff")
lb6.configure(highlightcolor="black")

lb6 = tk.Label(win, text = "Contact no")
lb6.place(relx=0.035, rely=0.830,height=29, width=300)
lb6.configure(activebackground="#ffffff")
lb6.configure(activeforeground="black")
lb6.configure(background="#ffffff")
lb6.configure(disabledforeground="#bfbfbf")
lb6.configure(font=font10)
lb6.configure(foreground="#000000")
lb6.configure(highlightbackground="#ffffff")
lb6.configure(highlightcolor="black")

lb6 = tk.Label(win, text = "Room no")
lb6.place(relx=0.035, rely=0.885,height=29, width=300)
lb6.configure(activebackground="#ffffff")
lb6.configure(activeforeground="black")
lb6.configure(background="#ffffff")
lb6.configure(disabledforeground="#bfbfbf")
lb6.configure(font=font10)
lb6.configure(foreground="#000000")
lb6.configure(highlightbackground="#ffffff")
lb6.configure(highlightcolor="black")

lb6 = tk.Label(win, text = "Mess Card")
lb6.place(relx=0.035, rely=0.940,height=29, width=300)
lb6.configure(activebackground="#ffffff")
lb6.configure(activeforeground="black")
lb6.configure(background="#ffffff")
lb6.configure(disabledforeground="#bfbfbf")
lb6.configure(font=font10)
lb6.configure(foreground="#000000")
lb6.configure(highlightbackground="#ffffff")
lb6.configure(highlightcolor="black")

aa = tk.StringVar()
e1 = tk.Entry(win, width = 20, textvariable = aa)
e1.place(relx=0.37, rely=0.16,height=28, relwidth=0.23)
e1.configure(background="white")
e1.configure(disabledforeground="#bfbfbf")
e1.configure(font=font10)
e1.configure(foreground="#000000")
e1.configure(highlightbackground="#ffffff")
e1.configure(highlightcolor="black")
e1.configure(insertbackground="black")
e1.configure(selectbackground="#e6e6e6")
e1.configure(selectforeground="black")


bb = tk.StringVar()
e2 = tk.Entry(win, width = 20, textvariable = bb)
e2.place(relx=0.37, rely=0.28,height=28, relwidth=0.23)
e2.configure(background="white")
e2.configure(disabledforeground="#bfbfbf")
e2.configure(font=font10)
e2.configure(foreground="#000000")
e2.configure(highlightbackground="#ffffff")
e2.configure(highlightcolor="black")
e2.configure(insertbackground="black")
e2.configure(selectbackground="#e6e6e6")
e2.configure(selectforeground="black")

cc = tk.StringVar()
e3 = tk.Entry(win, width = 20, textvariable = cc)
e3.place(relx=0.37, rely=0.335,height=28, relwidth=0.23)
e3.configure(background="white")
e3.configure(disabledforeground="#bfbfbf")
e3.configure(font=font10)
e3.configure(foreground="#000000")
e3.configure(highlightbackground="#ffffff")
e3.configure(highlightcolor="black")
e3.configure(insertbackground="black")
e3.configure(selectbackground="#e6e6e6")
e3.configure(selectforeground="black")


dd = tk.StringVar()
e4 = tk.Entry(win, width = 20, textvariable = dd)
e4.place(relx=0.37, rely=0.39,height=28, relwidth=0.23)
e4.configure(background="white")
e4.configure(disabledforeground="#bfbfbf")
e4.configure(font=font10)
e4.configure(foreground="#000000")
e4.configure(highlightbackground="#ffffff")
e4.configure(highlightcolor="black")
e4.configure(insertbackground="black")
e4.configure(selectbackground="#e6e6e6")
e4.configure(selectforeground="black")

ee = tk.StringVar()
e5 = tk.Entry(win, width = 20, textvariable = ee)
e5.place(relx=0.37, rely=0.445,height=28, relwidth=0.23)
e5.configure(background="white")
e5.configure(disabledforeground="#bfbfbf")
e5.configure(font=font10)
e5.configure(foreground="#000000")
e5.configure(highlightbackground="#ffffff")
e5.configure(highlightcolor="black")
e5.configure(insertbackground="black")
e5.configure(selectbackground="#e6e6e6")
e5.configure(selectforeground="black")

ff = tk.StringVar()
e6 = tk.Entry(win, width = 20, textvariable = ff)
e6.place(relx=0.37, rely=0.5,height=28, relwidth=0.23)
e6.configure(background="white")
e6.configure(disabledforeground="#bfbfbf")
e6.configure(font=font10)
e6.configure(foreground="#000000")
e6.configure(highlightbackground="#ffffff")
e6.configure(highlightcolor="black")
e6.configure(insertbackground="black")
e6.configure(selectbackground="#e6e6e6")
e6.configure(selectforeground="black")

gg = tk.StringVar()
e7 = tk.Entry(win, width = 20, textvariable = gg)
e7.place(relx=0.37, rely=0.555,height=28, relwidth=0.23)
e7.configure(background="white")
e7.configure(disabledforeground="#bfbfbf")
e7.configure(font=font10)
e7.configure(foreground="#000000")
e7.configure(highlightbackground="#ffffff")
e7.configure(highlightcolor="black")
e7.configure(insertbackground="black")
e7.configure(selectbackground="#e6e6e6")
e7.configure(selectforeground="black")

hh = tk.StringVar()
e8 = tk.Entry(win, width = 20, textvariable = hh)
e8.place(relx=0.37, rely=0.610,height=28, relwidth=0.23)
e8.configure(background="white")
e8.configure(disabledforeground="#bfbfbf")
e8.configure(font=font10)
e8.configure(foreground="#000000")
e8.configure(highlightbackground="#ffffff")
e8.configure(highlightcolor="black")
e8.configure(insertbackground="black")
e8.configure(selectbackground="#e6e6e6")
e8.configure(selectforeground="black")

ii = tk.StringVar()
e9 = tk.Entry(win, width = 20, textvariable = ii)
e9.place(relx=0.37, rely=0.665,height=28, relwidth=0.23)
e9.configure(background="white")
e9.configure(disabledforeground="#bfbfbf")
e9.configure(font=font10)
e9.configure(foreground="#000000")
e9.configure(highlightbackground="#ffffff")
e9.configure(highlightcolor="black")
e9.configure(insertbackground="black")
e9.configure(selectbackground="#e6e6e6")
e9.configure(selectforeground="black")

jj = tk.StringVar()
e10 = tk.Entry(win, width = 20, textvariable = jj)
e10.place(relx=0.37, rely=0.720,height=28, relwidth=0.23)
e10.configure(background="white")
e10.configure(disabledforeground="#bfbfbf")
e10.configure(font=font10)
e10.configure(foreground="#000000")
e10.configure(highlightbackground="#ffffff")
e10.configure(highlightcolor="black")
e10.configure(insertbackground="black")
e10.configure(selectbackground="#e6e6e6")
e10.configure(selectforeground="black")

kk = tk.StringVar()
e11 = tk.Entry(win, width = 20, textvariable = kk)
e11.place(relx=0.37, rely=0.775,height=28, relwidth=0.23)
e11.configure(background="white")
e11.configure(disabledforeground="#bfbfbf")
e11.configure(font=font10)
e11.configure(foreground="#000000")
e11.configure(highlightbackground="#ffffff")
e11.configure(highlightcolor="black")
e11.configure(insertbackground="black")
e11.configure(selectbackground="#e6e6e6")
e11.configure(selectforeground="black")

ll = tk.StringVar()
e11 = tk.Entry(win, width = 20, textvariable = ll)
e11.place(relx=0.37, rely=0.830,height=28, relwidth=0.23)
e11.configure(background="white")
e11.configure(disabledforeground="#bfbfbf")
e11.configure(font=font10)
e11.configure(foreground="#000000")
e11.configure(highlightbackground="#ffffff")
e11.configure(highlightcolor="black")
e11.configure(insertbackground="black")
e11.configure(selectbackground="#e6e6e6")
e11.configure(selectforeground="black")

mm = tk.StringVar()
e12 = tk.Entry(win, width = 20, textvariable = mm)
e12.place(relx=0.37, rely=0.885,height=28, relwidth=0.23)
e12.configure(background="white")
e12.configure(disabledforeground="#bfbfbf")
e12.configure(font=font10)
e12.configure(foreground="#000000")
e12.configure(highlightbackground="#ffffff")
e12.configure(highlightcolor="black")
e12.configure(insertbackground="black")
e12.configure(selectbackground="#e6e6e6")
e12.configure(selectforeground="black")

nn = tk.StringVar()
e13 = tk.Entry(win, width = 20, textvariable = nn)
e13.place(relx=0.37, rely=0.940,height=28, relwidth=0.23)
e13.configure(background="white")
e13.configure(disabledforeground="#bfbfbf")
e13.configure(font=font10)
e13.configure(foreground="#000000")
e13.configure(highlightbackground="#ffffff")
e13.configure(highlightcolor="black")
e13.configure(insertbackground="black")
e13.configure(selectbackground="#e6e6e6")
e13.configure(selectforeground="black")

def get():
    a = e1.get()
    cur.execute("select stuid from stu1 where stuid = '"+a+"'" )
    res = cur.fetchall()
    bb.set(res)
    
    cur.execute("select name from stu1 where stuid LIKE '"+a+"'" )
    res = cur.fetchall()
    cc.set(res)
    
    cur.execute("select rollno from stu1 where stuid LIKE '"+a+"'" )
    res = cur.fetchall()
    dd.set(res)
    
    cur.execute("select coursename from course where stuid LIKE '"+a+"'" )
    res = cur.fetchall()
    ee.set(res)
      
    cur.execute("select noofyears from course where stuid LIKE '"+a+"'" )
    i = 2
    res = cur.fetchall()
    for i in res:
        ff.set(i)

    cur.execute("select dob from stu1 where stuid LIKE '"+a+"'" )
    res = cur.fetchall()
    gg.set(res)
      
    cur.execute("select fname from stu1 where stuid LIKE '"+a+"'" )
    i = 2
    res = cur.fetchall()
    for i in res:
        hh.set(i)
      
    cur.execute("select mname from stu1 where stuid LIKE '"+a+"'" )
    res = cur.fetchall()
    for i in res:
        ii.set(i)
    
    cur.execute("select gender from stu1 where stuid LIKE '"+a+"'" )
    res = cur.fetchall()
    jj.set(res)
    
    cur.execute("select address from stu1 where stuid LIKE '"+a+"'" )
    res = cur.fetchall()
    for i in res:
        kk.set(i)
    
    cur.execute("select contactno from stu1 where stuid LIKE '"+a+"'" )
    res = cur.fetchall()
    ll.set(res)
    
    cur.execute("select roomno from stu1 where stuid LIKE '"+a+"'" )
    res = cur.fetchall()
    mm.set(res)
    
    cur.execute("select stuid from mess where stuid LIKE '"+a+"'" )
    res = cur.fetchall()
    
  
    if res != []: 
        y = ' yes'
        nn.set(y)
    else :
        n = ' no'
        nn.set(n)
    e1.Clear()
    con.commit()
    cur.close()
    #win.destroy()

btn = tk.Button(win , text = 'submit', command = get)
btn.place(relx=0.52, rely=0.214, height=35, width= 80)
btn.configure(activebackground="#ffffff")
btn.configure(activeforeground="#000000")
btn.configure(background="#ffffff")
btn.configure(disabledforeground="#bfbfbf")
btn.configure(font=font10)
btn.configure(foreground="#000000")
btn.configure(highlightbackground="#ffffff")
btn.configure(highlightcolor="black")
btn.configure(pady="0")
#self.Button4.configure(text='''SUBMIT''')
#self.Button4.configure(command=submit_clicked)

win.mainloop()

    
